name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: building_with_ai/alx-polly
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'building_with_ai/alx-polly/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Typecheck (CI tsconfig)
        run: npm run typecheck:ci
      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
        run: npm run build
